"""
PREDICT - Loads trained artifacts and predicts fraud probability.
Matches the 24 features generated by train_model.py from MulDiGraph.pkl
"""
import os, joblib
import numpy as np

MODEL_DIR     = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH    = os.path.join(MODEL_DIR, "fraud_model.pkl")
FEATURES_PATH = os.path.join(MODEL_DIR, "feature_columns.pkl")
SCALER_PATH   = os.path.join(MODEL_DIR, "scaler.pkl")

_model = _features = _scaler = None


def load_artifacts():
    global _model, _features, _scaler
    if _model is not None:
        return True
    if not os.path.exists(MODEL_PATH):
        print("[MODEL] fraud_model.pkl not found - run: python model/train_model.py")
        return False
    _model    = joblib.load(MODEL_PATH)
    _features = joblib.load(FEATURES_PATH) if os.path.exists(FEATURES_PATH) else None
    _scaler   = joblib.load(SCALER_PATH)   if os.path.exists(SCALER_PATH)   else None
    n = len(_features) if _features else '?'
    print(f"[MODEL] XGBoost loaded successfully | Features: {n}")
    return True


def build_feature_vector(tx: dict) -> np.ndarray:
    """
    Maps wallet-level stats to the exact 24-feature vector
    used during training on MulDiGraph.pkl
    """
    feat_list = _features if _features else [
        'sent_count',
        'sent_total',
        'sent_mean',
        'sent_max',
        'sent_min',
        'sent_std',
        'sent_unique_recv',
        'recv_count',
        'recv_total',
        'recv_mean',
        'recv_max',
        'recv_unique_send',
        'sent_active_span',
        'recv_active_span',
        'night_sent_count',
        'total_tx_count',
        'sent_recv_ratio',
        'unique_counterparts',
        'large_tx_flag',
        'zero_recv_flag',
        'high_fan_out',
        'high_activity',
        'night_ratio',
        'amount_volatility',
    ]

    vec = np.array(
        [float(tx.get(f, 0)) for f in feat_list],
        dtype=np.float32
    ).reshape(1, -1)

    if _scaler is not None:
        vec = _scaler.transform(vec)

    return vec


def rule_based_fallback(tx: dict) -> float:
    """Heuristic scorer when model not available."""
    score = 0.0
    amt   = float(tx.get('amount', 0))
    hour  = int(tx.get('hour', 12))
    if amt > 10:                  score += 0.35
    elif amt > 5:                 score += 0.20
    if hour < 6 or hour > 22:    score += 0.25
    if tx.get('high_activity'):   score += 0.20
    if tx.get('large_tx_flag'):   score += 0.15
    if tx.get('zero_recv_flag'):  score += 0.10
    if tx.get('high_fan_out'):    score += 0.10
    return min(score, 1.0)


def predict_fraud(tx: dict) -> dict:
    """
    Main entry point called by Flask API.
    Accepts a dict of wallet-level features.
    Returns fraud_probability, normal_probability, model_used.
    """
    loaded = load_artifacts()

    if loaded and _model is not None:
        try:
            vec   = build_feature_vector(tx)
            proba = _model.predict_proba(vec)[0]
            return {
                "fraud_probability"  : round(float(proba[1]), 4),
                "normal_probability" : round(float(proba[0]), 4),
                "model_used"         : "XGBoost (Ethereum Phishing Dataset — 2.97M nodes)",
            }
        except Exception as e:
            print(f"[MODEL] Prediction error: {e}")

    fp = rule_based_fallback(tx)
    return {
        "fraud_probability"  : round(fp, 4),
        "normal_probability" : round(1 - fp, 4),
        "model_used"         : "RuleBasedFallback",
    }
