/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace FraudDetection {
      
    export type ThresholdRecordStruct = {threshold: BigNumberish, fraudScore: BigNumberish, txCount: BigNumberish, amountWei: BigNumberish, timestamp: BigNumberish, prevHash: BytesLike}

    export type ThresholdRecordStructOutput = [threshold: bigint, fraudScore: bigint, txCount: bigint, amountWei: bigint, timestamp: bigint, prevHash: string] & {threshold: bigint, fraudScore: bigint, txCount: bigint, amountWei: bigint, timestamp: bigint, prevHash: string }
  

    export type TransactionRecordStruct = {txHash: string, sender: AddressLike, receiver: AddressLike, amountWei: BigNumberish, fraudScore: BigNumberish, threshold: BigNumberish, decision: string, action: string, timestamp: BigNumberish, exists: boolean}

    export type TransactionRecordStructOutput = [txHash: string, sender: string, receiver: string, amountWei: bigint, fraudScore: bigint, threshold: bigint, decision: string, action: string, timestamp: bigint, exists: boolean] & {txHash: string, sender: string, receiver: string, amountWei: bigint, fraudScore: bigint, threshold: bigint, decision: string, action: string, timestamp: bigint, exists: boolean }
  
    }

  export interface FraudDetectionInterface extends Interface {
    getFunction(nameOrSignature: "BLOCK_THRESHOLD_ETH" | "FREEZE_THRESHOLD_ETH" | "blacklisted" | "getThresholdCount" | "getThresholdHistory" | "getTotalTransactions" | "getTransaction" | "isBlacklisted" | "logTransaction" | "manualBlacklist" | "modelDeployedAt" | "modelHash" | "modelVersion" | "owner" | "records" | "registerModelHash" | "removeBlacklist" | "thresholdHistory" | "txHashes" | "updateWalletThreshold" | "verifyModelHash" | "walletLastThreshold" | "walletTxCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AlertTriggered" | "ModelHashRegistered" | "ThresholdUpdated" | "TransactionLogged" | "WalletBlacklisted"): EventFragment;

    encodeFunctionData(functionFragment: 'BLOCK_THRESHOLD_ETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'FREEZE_THRESHOLD_ETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'blacklisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getThresholdCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getThresholdHistory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalTransactions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTransaction', values: [string]): string;
encodeFunctionData(functionFragment: 'isBlacklisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'logTransaction', values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'manualBlacklist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'modelDeployedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'modelHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'modelVersion', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'records', values: [string]): string;
encodeFunctionData(functionFragment: 'registerModelHash', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'removeBlacklist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'thresholdHistory', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'txHashes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateWalletThreshold', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyModelHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'walletLastThreshold', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'walletTxCount', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BLOCK_THRESHOLD_ETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FREEZE_THRESHOLD_ETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getThresholdCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getThresholdHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalTransactions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBlacklisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manualBlacklist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'modelDeployedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'modelHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'modelVersion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerModelHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeBlacklist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'thresholdHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'txHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateWalletThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyModelHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletLastThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletTxCount', data: BytesLike): Result;
  }

  
    export namespace AlertTriggeredEvent {
      export type InputTuple = [sender: AddressLike, message: string, timestamp: BigNumberish];
      export type OutputTuple = [sender: string, message: string, timestamp: bigint];
      export interface OutputObject {sender: string, message: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModelHashRegisteredEvent {
      export type InputTuple = [hash: BytesLike, version: string, timestamp: BigNumberish];
      export type OutputTuple = [hash: string, version: string, timestamp: bigint];
      export interface OutputObject {hash: string, version: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdUpdatedEvent {
      export type InputTuple = [wallet: AddressLike, threshold: BigNumberish, fraudScore: BigNumberish, txCount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [wallet: string, threshold: bigint, fraudScore: bigint, txCount: bigint, timestamp: bigint];
      export interface OutputObject {wallet: string, threshold: bigint, fraudScore: bigint, txCount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionLoggedEvent {
      export type InputTuple = [txHash: string, sender: AddressLike, decision: string, action: string, fraudScore: BigNumberish, threshold: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [txHash: string, sender: string, decision: string, action: string, fraudScore: bigint, threshold: bigint, timestamp: bigint];
      export interface OutputObject {txHash: string, sender: string, decision: string, action: string, fraudScore: bigint, threshold: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WalletBlacklistedEvent {
      export type InputTuple = [wallet: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [wallet: string, timestamp: bigint];
      export interface OutputObject {wallet: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FraudDetection extends BaseContract {
    
    connect(runner?: ContractRunner | null): FraudDetection;
    waitForDeployment(): Promise<this>;

    interface: FraudDetectionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BLOCK_THRESHOLD_ETH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FREEZE_THRESHOLD_ETH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    blacklisted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getThresholdCount: TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getThresholdHistory: TypedContractMethod<
      [wallet: AddressLike, ],
      [FraudDetection.ThresholdRecordStructOutput[]],
      'view'
    >
    

    
    getTotalTransactions: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTransaction: TypedContractMethod<
      [h: string, ],
      [FraudDetection.TransactionRecordStructOutput],
      'view'
    >
    

    
    isBlacklisted: TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    logTransaction: TypedContractMethod<
      [txHash: string, sender: AddressLike, receiver: AddressLike, amountWei: BigNumberish, fraudScore: BigNumberish, threshold: BigNumberish, decision: string, action: string, ],
      [void],
      'nonpayable'
    >
    

    
    manualBlacklist: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    modelDeployedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    modelHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    modelVersion: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    records: TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, bigint, bigint, bigint, string, string, bigint, boolean] & {txHash: string, sender: string, receiver: string, amountWei: bigint, fraudScore: bigint, threshold: bigint, decision: string, action: string, timestamp: bigint, exists: boolean }],
      'view'
    >
    

    
    registerModelHash: TypedContractMethod<
      [hash: BytesLike, version: string, ],
      [void],
      'nonpayable'
    >
    

    
    removeBlacklist: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    thresholdHistory: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, string] & {threshold: bigint, fraudScore: bigint, txCount: bigint, amountWei: bigint, timestamp: bigint, prevHash: string }],
      'view'
    >
    

    
    txHashes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    updateWalletThreshold: TypedContractMethod<
      [wallet: AddressLike, threshold: BigNumberish, fraudScore: BigNumberish, amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifyModelHash: TypedContractMethod<
      [currentHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    walletLastThreshold: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    walletTxCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BLOCK_THRESHOLD_ETH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FREEZE_THRESHOLD_ETH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'blacklisted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getThresholdCount'): TypedContractMethod<
      [wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getThresholdHistory'): TypedContractMethod<
      [wallet: AddressLike, ],
      [FraudDetection.ThresholdRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalTransactions'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTransaction'): TypedContractMethod<
      [h: string, ],
      [FraudDetection.TransactionRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isBlacklisted'): TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'logTransaction'): TypedContractMethod<
      [txHash: string, sender: AddressLike, receiver: AddressLike, amountWei: BigNumberish, fraudScore: BigNumberish, threshold: BigNumberish, decision: string, action: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'manualBlacklist'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'modelDeployedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'modelHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'modelVersion'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, bigint, bigint, bigint, string, string, bigint, boolean] & {txHash: string, sender: string, receiver: string, amountWei: bigint, fraudScore: bigint, threshold: bigint, decision: string, action: string, timestamp: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'registerModelHash'): TypedContractMethod<
      [hash: BytesLike, version: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeBlacklist'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'thresholdHistory'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, string] & {threshold: bigint, fraudScore: bigint, txCount: bigint, amountWei: bigint, timestamp: bigint, prevHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'txHashes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateWalletThreshold'): TypedContractMethod<
      [wallet: AddressLike, threshold: BigNumberish, fraudScore: BigNumberish, amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyModelHash'): TypedContractMethod<
      [currentHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'walletLastThreshold'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'walletTxCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'AlertTriggered'): TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
getEvent(key: 'ModelHashRegistered'): TypedContractEvent<ModelHashRegisteredEvent.InputTuple, ModelHashRegisteredEvent.OutputTuple, ModelHashRegisteredEvent.OutputObject>;
getEvent(key: 'ThresholdUpdated'): TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'TransactionLogged'): TypedContractEvent<TransactionLoggedEvent.InputTuple, TransactionLoggedEvent.OutputTuple, TransactionLoggedEvent.OutputObject>;
getEvent(key: 'WalletBlacklisted'): TypedContractEvent<WalletBlacklistedEvent.InputTuple, WalletBlacklistedEvent.OutputTuple, WalletBlacklistedEvent.OutputObject>;

    filters: {
      
      'AlertTriggered(address,string,uint256)': TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
      AlertTriggered: TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
    

      'ModelHashRegistered(bytes32,string,uint256)': TypedContractEvent<ModelHashRegisteredEvent.InputTuple, ModelHashRegisteredEvent.OutputTuple, ModelHashRegisteredEvent.OutputObject>;
      ModelHashRegistered: TypedContractEvent<ModelHashRegisteredEvent.InputTuple, ModelHashRegisteredEvent.OutputTuple, ModelHashRegisteredEvent.OutputObject>;
    

      'ThresholdUpdated(address,uint256,uint256,uint256,uint256)': TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
      ThresholdUpdated: TypedContractEvent<ThresholdUpdatedEvent.InputTuple, ThresholdUpdatedEvent.OutputTuple, ThresholdUpdatedEvent.OutputObject>;
    

      'TransactionLogged(string,address,string,string,uint256,uint256,uint256)': TypedContractEvent<TransactionLoggedEvent.InputTuple, TransactionLoggedEvent.OutputTuple, TransactionLoggedEvent.OutputObject>;
      TransactionLogged: TypedContractEvent<TransactionLoggedEvent.InputTuple, TransactionLoggedEvent.OutputTuple, TransactionLoggedEvent.OutputObject>;
    

      'WalletBlacklisted(address,uint256)': TypedContractEvent<WalletBlacklistedEvent.InputTuple, WalletBlacklistedEvent.OutputTuple, WalletBlacklistedEvent.OutputObject>;
      WalletBlacklisted: TypedContractEvent<WalletBlacklistedEvent.InputTuple, WalletBlacklistedEvent.OutputTuple, WalletBlacklistedEvent.OutputObject>;
    
    };
  }